name: myfirstflutterapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_svg: ^2.1.6
  intl: ^0.20.2
  shared_preferences: ^2.3.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  flutter_native_splash: ^2.4.0
  bootstrap_icons: ^1.11.0
  signalr_netcore: ^1.4.3
  http: ^1.5.0
  provider: ^6.1.5+1
  timeago: ^3.6.1
  shimmer: ^3.0.0
  overlay_support: ^2.1.0
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  http_parser: ^4.1.2
  google_maps_flutter: ^2.12.3
  webview_flutter: ^4.13.0
  flutter_cashfree_pg_sdk: ^2.2.9+47
  flutter_localizations:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  razorpay_flutter: ^1.4.0
permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/constant/empty-user-profilepic.webp

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/constant/ic_launcher.png"

flutter_native_splash:
  color: "#E00707" # This is the background color (white)
  image: assets/icons/splash_screen.png

android_12:
  color: "#FFF5F5"
  image: assets/icons/splash_screen.png
  branding: assets/icons/splash_screen.png