name: myfirstflutterapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_svg: ^2.1.6
  intl: ^0.20.2
  shared_preferences: ^2.3.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
