// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4OhYQ02YHbiJCgfLGXxoQxYeVSJt-Iqo',
    appId: '1:282360864740:web:acfb8964855dee8324b1f1',
    messagingSenderId: '282360864740',
    projectId: 'p2p-app-flutter',
    authDomain: 'p2p-app-flutter.firebaseapp.com',
    storageBucket: 'p2p-app-flutter.firebasestorage.app',
    measurementId: 'G-18C7FF6NQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4nsL7J77gjGAXeS4MDxrFDX9Fuf68MwQ',
    appId: '1:282360864740:android:a0b0a7a3a01d893524b1f1',
    messagingSenderId: '282360864740',
    projectId: 'p2p-app-flutter',
    storageBucket: 'p2p-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWJGbydBQ7Sc-x1LaV7F1gXWax9OxekTo',
    appId: '1:282360864740:ios:d96fa9cec5037aef24b1f1',
    messagingSenderId: '282360864740',
    projectId: 'p2p-app-flutter',
    storageBucket: 'p2p-app-flutter.firebasestorage.app',
    androidClientId: '282360864740-eeba8he5hf405ninp9mrpasts78irbnb.apps.googleusercontent.com',
    iosClientId: '282360864740-oorhsftbvgb7r2cjg403o8i8q0pa1ekh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWJGbydBQ7Sc-x1LaV7F1gXWax9OxekTo',
    appId: '1:282360864740:ios:d96fa9cec5037aef24b1f1',
    messagingSenderId: '282360864740',
    projectId: 'p2p-app-flutter',
    storageBucket: 'p2p-app-flutter.firebasestorage.app',
    androidClientId: '282360864740-eeba8he5hf405ninp9mrpasts78irbnb.apps.googleusercontent.com',
    iosClientId: '282360864740-oorhsftbvgb7r2cjg403o8i8q0pa1ekh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4OhYQ02YHbiJCgfLGXxoQxYeVSJt-Iqo',
    appId: '1:282360864740:web:bcc925745f6b28fc24b1f1',
    messagingSenderId: '282360864740',
    projectId: 'p2p-app-flutter',
    authDomain: 'p2p-app-flutter.firebaseapp.com',
    storageBucket: 'p2p-app-flutter.firebasestorage.app',
    measurementId: 'G-41Q7MSTRPR',
  );
}
